name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@develop

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@develop
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build